name: livefeed
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^1.2.5
  meta: ^1.2.4
  formz: ^0.3.2
  pinput: ^0.2.6
  dotted_border: ^1.0.7
  flutter_countdown_timer: ^1.5.0
  syncfusion_flutter_gauges: ^18.3.53
  flutter_staggered_grid_view: ^0.3.3
  flutter_xlider: ^3.4.0
  chewie: ^1.0.0
  video_player: ^2.0.2
  image_picker: ^0.6.7+11
  country_pickers: ^2.0.0
  badges: ^1.1.6
  geolocator: ^6.1.13
  geocoding: ^1.0.5
  fdottedline: ^1.0.1
  url_launcher: ^5.7.10
  drop_cap_text: ^1.0.7
  sortedmap: ^0.4.2+1
  email_validator: ^1.0.6
  uuid: ^2.2.2
  visibility_detector: ^0.1.5
  flutter_windowmanager: ^0.0.2
  sms_autofill: ^2.0.0
  # fluttercontactpicker: ^4.2.1
  video_thumbnail: ^0.2.5+1
  square_in_app_payments: ^1.4.0
  repository_core:
    path: packages/repository_core
  swagger_api:
    path: packages/swagger_api
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.4
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
        - asset: assets/fonts/Gilroy-Light.otf
  assets:
    - assets/images/earth_exp.png
    - assets/images/earth_exp2x.png
    - assets/images/earth_exp3x.png
    - assets/images/earth.png
    - assets/images/earth2x.png
    - assets/images/earth3x.png
    - assets/images/livefeed_logo.png
    - assets/images/livefeed_logo2x.png
    - assets/images/livefeed_logo3x.png
    - assets/images/upload_image.png
    - assets/images/upload_image2x.png
    - assets/images/upload_image3x.png
    - assets/images/shocked.png
    - assets/images/shocked2x.png
    - assets/images/shocked3x.png
    - assets/images/connection_links.png
    - assets/images/connection_links2x.png
    - assets/images/connection_links3x.png
    - assets/images/sibabalwe.png
    - assets/images/sibabalwe2x.png
    - assets/images/sibabalwe3x.png
    - assets/images/shoes.png
    - assets/images/shoes2x.png
    - assets/images/shoes3x.png
    - assets/images/ad_poster.png
    - assets/images/ad_poster2x.png
    - assets/images/ad_poster3x.png
    - assets/images/medicine_guy.png
    - assets/images/medicine_guy2x.png
    - assets/images/medicine_guy3x.png
    - assets/images/facebook_icon.png
    - assets/images/facebook_icon2x.png
    - assets/images/facebook_icon3x.png
    - assets/images/twitter_icon.png
    - assets/images/twitter_icon2x.png
    - assets/images/twitter_icon3x.png
    - assets/images/reddit_icon.png
    - assets/images/reddit_icon2x.png
    - assets/images/reddit_icon3x.png
    - assets/images/instagram_icon.png
    - assets/images/instagram_icon2x.png
    - assets/images/instagram_icon3x.png
    - assets/images/landu.png
    - assets/images/landu2x.png
    - assets/images/landu3x.png
    - assets/images/rocket_car.png
    - assets/images/rocket_car2x.png
    - assets/images/rocket_car3x.png
    - assets/images/marketplace_browse.png
    - assets/images/marketplace_browse2x.png
    - assets/images/marketplace_browse3x.png
    - assets/images/blogger_girl.png
    - assets/images/blogger_girl2x.png
    - assets/images/blogger_girl3x.png
    - assets/images/contact_us_how.png
    - assets/images/contact_us_how2x.png
    - assets/images/contact_us_how3x.png
    - assets/images/livefeed_logo_how.png
    - assets/images/livefeed_logo_how2x.png
    - assets/images/livefeed_logo_how3x.png
    - assets/images/otp_how.png
    - assets/images/otp_how2x.png
    - assets/images/otp_how3x.png
    - assets/images/sign_up_how.png
    - assets/images/sign_up_how2x.png
    - assets/images/sign_up_how3x.png
    - assets/images/update_phone_how.png
    - assets/images/update_phone_how2x.png
    - assets/images/update_phone_how3x.png
    - assets/images/india_festival.png
    - assets/images/india_festival2x.png
    - assets/images/india_festival3x.png
    - assets/images/fashion_ad.png
    - assets/images/fashion_ad2x.png
    - assets/images/fashion_ad3x.png
    - assets/images/target_profile_post.png
    - assets/images/target_profile_post2x.png
    - assets/images/target_profile_post3x.png
    - assets/images/target_profile.png
    - assets/images/target_profile2x.png
    - assets/images/target_profile3x.png
    - assets/images/target_post.png
    - assets/images/target_post2x.png
    - assets/images/target_post3x.png
    - assets/images/feather.png
    - assets/images/feather2x.png
    - assets/images/feather3x.png
    - assets/images/cloud_computing.png
    - assets/images/cloud_computing2x.png
    - assets/images/cloud_computing3x.png
    - assets/images/local_global.png
    - assets/images/local_global2x.png
    - assets/images/local_global3x.png
    - assets/images/affordable.png
    - assets/images/affordable2x.png
    - assets/images/affordable3x.png
    - assets/images/full_control.png
    - assets/images/full_control2x.png
    - assets/images/full_control3x.png
    - assets/images/pen.png
    - assets/images/pen2x.png
    - assets/images/pen3x.png
    - assets/images/delete.png
    - assets/images/delete2x.png
    - assets/images/delete3x.png
    - assets/images/worldwide_layers.png
    - assets/images/worldwide_layers2x.png
    - assets/images/worldwide_layers3x.png
    - assets/images/local_layers.png
    - assets/images/local_layers2x.png
    - assets/images/local_layers3x.png
    - assets/images/robot.png
    - assets/images/robot2x.png
    - assets/images/robot3x.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
